# Главная цель 
Curs_Work: MusicalComposition.o main.o
	gcc main.o MusicalComposition.o -o Curs_Work

# Объектный файл для функции main
main.o: main.cpp
	gcc -c main.cpp

# Объектный файл для функции работы со списком Musical_Composition
MusicalComposition.o: Musical_Composition.cpp
	gcc -c Musical_Composition.cpp

# Очистка от объектных файлов после сборки проекта
clean:
	rm -rf *.o